<?php
/**
 * form.php
 * The HTML generated by DKO-category-widget
 */
defined('ABSPATH') or die('Cannot access pages directly.');

//reasons to fail
if (empty($this->widget['fields'])) return false;

$defaults = array(
  'id'    => '',
  'name'  => '',
  'desc'  => '',
  'type'  => '',
  'options' => '',
  'std'   => '',
);

do_action('DKO_Category_Widget_before');
foreach ($this->widget['fields'] as $field) {
  //making sure we don't throw strict errors
  $field = wp_parse_args($field, $defaults);

  $meta = false;
  if (isset($field['id']) && array_key_exists($field['id'], $instance)) {
    @$meta = attribute_escape($instance[$field['id']]);
  }

  if ($field['type'] != 'custom' && $field['type'] != 'metabox') {
    echo '<p><label for="',$this->get_field_id($field['id']),'">';
  }
  if (isset($field['name']) && $field['name']) echo $field['name'],':';

  switch ($field['type']) {
    case 'text':
      echo '<input type="text" size="14" name="', $this->get_field_name($field['id']), '" id="', $this->get_field_id($field['id']), '" value="', ($meta ? $meta : @$field['std']), '" class="vibe_text" />', 
      '<br/><span class="description">', @$field['desc'], '</span>';
      break;
    case 'textarea':
      echo '<textarea class="vibe_textarea" name="', $this->get_field_name($field['id']), '" id="', $this->get_field_id($field['id']), '" cols="60" rows="4" style="width:97%">', $meta ? $meta : @$field['std'], '</textarea>', 
      '<br/><span class="description">', @$field['desc'], '</span>';
      break;
    case 'select':
      echo '<select class="vibe_select" name="', $this->get_field_name($field['id']), '" id="', $this->get_field_id($field['id']), '">';

      foreach ($field['options'] as $value => $option) {
          $selected_option = ( $value ) ? $value : $option;
          echo '<option', ($value ? ' value="' . $value . '"' : ''), ($meta == $selected_option ? ' selected="selected"' : ''), '>', $option, '</option>';
      }

      echo '</select>',
      '<br/><span class="description">', @$field['desc'], '</span>';
      break;
    case 'custom':
      echo $field['std'];
      break;
  }

  if ($field['type'] != 'custom' && $field['type'] != 'metabox') {
    echo '</label></p>';
  }
}
do_action('DKO_Category_Widget_after');
return true;
