<?php
/**
 * view.php
 * The HTML generated by DKO-category-widget
 */
defined('ABSPATH') or die('Cannot access pages directly.');
?>
<h2><a href="<?php echo $category_link; ?>"><?php echo $widget_title; ?> <span class="ir icon-subcategory"></span></a></h2>
<section>
  <?php $dko_category_widget_query->the_post(); ?>
  <article class="latest">
    <a href="<?php the_permalink(); ?>" class="inner">
      <?php the_post_thumbnail(array(235, 160)); ?>
      <h3><?php the_title(); ?></h3>
      <?php $single_tag = get_single_tag(); if ($single_tag): ?>
        <em class="meta">filed under <span class="tag"><?php echo $single_tag->name; ?></span></em>
      <?php endif; ?>
      <div class="excerpt">
        <?php the_excerpt(); ?>
        <span class="read-more">Read more...</span>
      </div>
    </a><!-- /.inner -->
  </article>
  <?php while ($dko_category_widget_query->have_posts()): $dko_category_widget_query->the_post(); ?>
    <article class="another">
      <a href="<?php the_permalink(); ?>" class="inner">
        <h3><?php the_title(); ?></h3>
        <span class="read-more">Read more...</span>
      </a><!-- /.inner -->
    </article>
  <?php endwhile; ?>
</section>
