<?php
/**
 * view.php
 * The HTML generated by DKO-category-widget
 */
defined('ABSPATH') or die('Cannot access pages directly.');
?>
<h2><a href="<?php echo $category_link; ?>"><?php echo $widget_title; ?> <span class="ir icon-subcategory"></span></a></h2>
<section>
  <?php $dko_category_widget_query->the_post(); ?>
  <article class="latest">
    <div class="inner">
      <a href="<?php the_permalink(); ?>" class="thumbnail"><?php the_post_thumbnail(array(235, 160)); ?></a>
      <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
      <?php $single_tag = get_single_tag(); if ($single_tag): ?>
        <em class="meta">filed under <a><?php echo $single_tag->name; ?></a></em>
      <?php endif; ?>
      <div class="excerpt">
        <?php the_excerpt(); ?>
        <a href="<?php the_permalink(); ?>" class="read-more">Read more...</a>
      </div>
    </div><!-- /.inner -->
  </article>
  <?php while ($dko_category_widget_query->have_posts()): $dko_category_widget_query->the_post(); ?>
    <article class="another">
      <div class="inner">
        <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
        <a href="<?php the_permalink(); ?>" class="read-more">Read more...</a>
      </div><!-- /.inner -->
    </article>
  <?php endwhile; ?>
</section>
